data_dir: "/nakama/data/"
runtime:
  path: '/nakama/modules/'
  http_key: defaulthttpkey
logger:
  level: "DEBUG"
  stdout: true
session:
  token_expiry_sec: 86400 # one day
  refresh_token_expiry_sec: 2629800 # one month
  single_socket: true
  single_match: true